Finished my homework
ucu-computer-science/UCU_Linux_Club pull request #10
Opened 2020-10-26 09:38 UTC by shevdan

Finished task 1, will do other tasks later.

2020-11-06 00:18 UTC, Fenix-125 requested changes
1. використано неіснуючу команду так не очщено від сміття
2. немає

2020-11-06 00:18 UTC, Fenix-125 commented on homework/shevchuk_bohdan/week2/ip_adress.sh
> +ipconfig getifaddr en0
- такої команди на arch linux нема, треба було використати ```ip a ```
- і потрібно виводити тільки свій ip

2020-11-06 10:32 UTC, LastGenius-edu commented
@shevdan if you have any questions, let us know. Otherwise I'll close this pull request :)

2020-11-07 13:42 UTC, shevdan commented on homework/shevchuk_bohdan/week2/ip_adress.sh
> +ipconfig getifaddr en0
на маку ця команда працює нормально) а ip на макос немає наче

2020-11-07 22:39 UTC, closed without merging