Finished homework
ucu-computer-science/UCU_Linux_Club pull request #12
Opened 2020-10-26 14:59 UTC by Adeon18

:D

2020-10-29 21:46 UTC, Adeon18 commented
Added homework with bash

2020-11-06 00:12 UTC, Fenix-125 requested changes
2 завдання виконане (раджу попробувати переробити)
1 завдання неправильний ip адрес виводить

2020-11-06 00:12 UTC, Fenix-125 commented on homework/ostap_trush/week2/script1
> +curl ifconfig.me
це не ip адреса твого компа це адреса твого роутера ззовні
тобі треба було використати команду ```ip a```

2020-11-06 00:12 UTC, Fenix-125 commented on homework/ostap_trush/week2/script2
> +pacman -Q | grep 'ba\|apps\|cs' | awk '{printf "%s->",$1} END {print ""}'
**жостко!** (за awk респект)
але тут треба було використати ``` cut ```,  ``` tr ```, and  ``` sed ```

2020-11-06 10:32 UTC, LastGenius-edu commented
@Adeon18 if you have any questions, let us know. Otherwise I'll close this pull request :)

2020-11-07 22:40 UTC, closed without merging