Finished my homework and added info to readme
ucu-computer-science/UCU_Linux_Club pull request #15
Opened 2020-10-26 18:26 UTC by berdychiv

Just a test pull request. Don't mind

2020-11-05 23:58 UTC, Fenix-125 requested changes
- оформити скрипти в окремих відповідних файлах
- переробити перше завдання
- 2 завдання нема

2020-11-05 23:58 UTC, Fenix-125 commented on homework/tkachyshyn_nastia/week2/homework.md
> +1. echo $(hostname -i)
чотко але краще попробуй використати як сорс ip адреси комаду ```ip a```
і це труба було скробити окремим скриптом а не текстом тут

2020-11-05 23:58 UTC, Fenix-125 commented on homework/tkachyshyn_nastia/week2/homework.md
> +2. local/appstream-glib 0.7.18-1->local/archlinux-appstream-data 20200720-1.1->local/electron5 5.0.13-7->local/pamac-cli 9.5.12-1->local/pamac-common 9.5.12-1->local/pamac-gtk 9.5.12-1->local/xapp 1.
руцями це робилось ? :=)
тут не треба версію програми лишати

2020-11-06 10:31 UTC, LastGenius-edu commented
@berdychiv  if you have any questions, let us know. Otherwise I'll close this pull request :)

2020-11-07 22:40 UTC, closed without merging