partly done homework
ucu-computer-science/UCU_Linux_Club pull request #17
Opened 2020-10-26 22:12 UTC by YaroslavM25

2020-10-26 23:23 UTC, YaroslavM25 commented
Sorry for being late))

2020-10-26 23:25 UTC, LastGenius-edu commented
> Sorry for being late))

Get some sleep, Linux Club isn't really worth it -_-

2020-11-05 23:52 UTC, Fenix-125 requested changes
## Завдання
1. неправильно працює (виводить ip з сміттям)
2. неправильно працює (виводить назву програми з версією)
3. неправильно працює (не виконує команди)

2020-11-05 23:52 UTC, Fenix-125 commented on homework/moskalyk_yaroslav/week2/get_ip
> +ip a | grep 'inet '
виводить зайве сміття з ip адресою
повино виводити суто ip адресу. приклад:  192.168.0.1

2020-11-05 23:52 UTC, Fenix-125 commented on homework/moskalyk_yaroslav/week2/get_matching_programs
> +pacman -Q | grep "ba\|cs|\apps" | sed ':a;N;$!ba;s/\n/->/g'
- кожег рядок dbdjle rjvfylb pacman -Q має таку структуру: "program_name version" (e.g. "xz 5.2.5-1"). Отож в тебе прінтиться не то. Тут потрібно було скористатись утилітою cut.

2020-11-05 23:52 UTC, Fenix-125 commented on homework/moskalyk_yaroslav/week2/keylogger
> +	read -p "$ " command
а хто команду буде виконувати :=)

2020-11-06 10:31 UTC, LastGenius-edu commented
@YaroslavM25  if you have any questions, let us know. Otherwise I'll close this pull request :)

2020-11-07 22:40 UTC, closed without merging