Have done first 2 tasks of the first homework.
ucu-computer-science/UCU_Linux_Club pull request #19
Opened 2020-10-29 21:02 UTC by bogdanmagometa

2020-11-05 23:33 UTC, Fenix-125 requested changes
## Завдання
1. не працює (нічого не виводить)
2. працює не так як треба
3. немає (ок)

2020-11-05 23:33 UTC, Fenix-125 commented on homework/mahometa_bohdan/week2/cs_ba_apps
> +for i in $(pacman -Q | grep -i -e cs -e ba -e apps)
- кожег рядок dbdjle rjvfylb ```pacman -Q``` має таку структуру: "program_name version" (e.g. "xz 5.2.5-1"). Отож в тебе прінтиться не то. Тут потрібно було скористатись утилітою ```cut```.
- це дуже круто, що ти використав ```for```, але тут була суть використати утиліти які редактують текст з стріму. Такі як: ```sed```, ```tr```

2020-11-05 23:33 UTC, Fenix-125 commented on homework/mahometa_bohdan/week2/cs_ba_apps
> +# для чого це писати?
> The #! syntax used in scripts to indicate an interpreter for execution under UNIX / Linux operating systems. Most Linux shell and perl / python script starts with. ([source](https://bash.cyberciti.biz/guide/Shebang))

2020-11-05 23:33 UTC, Fenix-125 commented on homework/mahometa_bohdan/week2/print_ip
> +#!/usr/bin/env bash
shebang працює лише в першому рядочку

2020-11-05 23:33 UTC, Fenix-125 commented on homework/mahometa_bohdan/week2/cs_ba_apps
> +#!/usr/bin/env bash
Утиліта ```env``` шукає переданий їй аргумент в PATH, тобто шукає інтерпритатор для цього скріпта.

2020-11-05 23:33 UTC, Fenix-125 commented on homework/mahometa_bohdan/week2/print_ip
> +ip a | grep wlo | grep inet | tr -s ' ' | cut -d' ' -f3 | cut -d'/' -f1
1. команда не виводить нічого
2. два grep писати не рентабильно
    - такий пошук можна написати ```regeks``` або за допомогою кількох виразів наданих одній команді
    - тут достатньо ```grep inet``` другий grep нідочого

2020-11-06 10:30 UTC, LastGenius-edu commented
@bogdanmagometa if you have any questions, let us know. Otherwise I'll close this pull request :)

2020-11-07 22:39 UTC, closed without merging